name: jobpulse
version: "2.0.0"
config-version: 2
profile: jobpulse
model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
clean-targets: ["target", "dbt_packages"]

models:
  jobpulse:
    staging:
      +schema: analytics
      +materialized: view
    dimensions:
      +schema: analytics
      +materialized: table
    marts:
      +schema: analytics
      +materialized: table
